---
title: "Graphics with ggplot2"
author: "jenny"
date: "9/28/2019"
output: html_document
---

# Learning ggplot2

We're learning ggplot2 It's going to be amazing.

```{r}
library(tidyverse) ## do this every time you start R and need it
```

```{r}
ohi_data <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_global_data.csv")
```

## DATA SUMMARIES

```{r}
head(ohi_data)
```

```{r}
summary(ohi_data)
```

```{r}
table(ohi_data$georegion_one)
table(ohi_data$georegion_two)
```

## PLOTS

```{r}
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI)) + geom_point()
```

```{r}
ggplot(data = ohi_data, aes(x = georegion_one, y = OHI_score)) + geom_point()
```

```{r}
ggplot(data = ohi_data, aes(x = georegion_one, y = OHI_score)) + geom_jitter(width=0.2)
```

```{r}
ggplot(data = ohi_data, aes(x = georegion_one)) + geom_bar()
```

```{r}
ggplot(data = ohi_data, aes(x = HDI)) + geom_histogram()
```

```{r}
# load in a new data set that summarizes OHI scores by georegion

ohi_summary <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/OHI_scores_georegion_summary.csv")

ohi_summary
```

```{r}
ggplot(data = ohi_summary, aes(x = georegions, y = OHI_score_average)) + 
  geom_bar(stat="identity") +
  geom_jitter(data=ohi_data, aes(x=georegion_one, y=OHI_score))
```

```{r}
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, size = coastal_pop)) + 
  geom_point()
```

```{r}
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, color = coastal_pop)) + 
  geom_point()
```

```{r}
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, color = georegion_one)) + 
  geom_point()
```

```{r}
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, shape = georegion_one)) + 
  geom_point()
```

```{r}
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, label=country)) + 
  geom_point(aes(x = OHI_score, y = HDI)) + geom_text()
```

## THEMES

```{r}
ggplot(data = ohi_data, aes(x = OHI_score, y = HDI)) + 
  geom_point() + 
  theme_bw()
```

# here are a bunch of themes: https://www.ggplot2-exts.org/

```{r}
source('https://raw.githubusercontent.com/OHI-Science/ohiprep/master/src/R/scatterTheme.txt')       

ggplot(data = ohi_data, aes(x = OHI_score, y = HDI)) + 
  geom_point() + 
  scatterTheme
```

## Customizing

```{r}
ggplot(data = ohi_data, aes(y = OHI_score, x = HDI, color=georegion_one)) + # data specific customization goes intise the aes function, while global changes go outside aes function
    labs(y = "OHI score, 2017",
       x = "Human Development Index",
       title = "Countries with high human development have more sustainable oceans",
      color = "Georegion") +  # if color doesn't work, use "fill"
     theme_bw()
```

```{r}
ggplot(data = ohi_data, aes(x=OHI_score)) +
 geom_histogram(fill="lightgray")
```

```{r}
ggplot(data = ohi_data, aes(x=OHI_score)) + # data specific customization goes intise the aes function, while global changes go outside aes function
 geom_histogram(fill="lightgray") +
  labs(x = "OHI Score", y = "")
```

```{r}
ggplot(data = ohi_data, aes(x=OHI_score)) +
 geom_histogram() + # the plot created in question 1 continued...
  labs(x = "OHI score",
       y = "Number of countries",
       title = "Distribution of OHI scores") +
  theme_light() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
        axis.text.y = element_text(size = 14),
        axis.title = element_text(size = 16)
        )
```

## Global custom changes

```{r}
ggplot(data = ohi_summary, aes(x = georegions, y = OHI_score_average)) + 
  geom_bar(stat="identity", fill = "lightgray") +
  geom_jitter(data=ohi_data, aes(x=georegion_one, y=OHI_score), color="red", size=3, alpha=0.4) +
  theme_bw()
```

## Cheat sheet - https://rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf

## Color palettes - http://colorbrewer2.org/

```{r}
library("RColorBrewer")
library("colorspace")
display.brewer.all()
```

```{r}
# using a continuous color scale
continuous_palette <- brewer.pal(n=9, "YlOrRd") #set a palette

```

```{r}
library(tidyverse)
ggplot(data = ohi_data, aes(x = OHI_score, y = OHI_trend, color = HDI)) + 
  geom_point(size =3) +
  scale_colour_gradientn(colors = continuous_palette)
```

```{r}
# using a discrete color scale
discrete_palette <- brewer.pal(n=12, "Set3")

ggplot(data = ohi_data, aes(x = OHI_score, y = HDI, color = georegion_one)) + 
  geom_point(size = 3) +
  scale_color_manual(values = discrete_palette)
```

